/* This SAS program was automatically generated by Stat/Transfer ver.14.2.1096.0306 */

/* ENCODING ISO-8859-15 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile '/Users/almichae/Dropbox (MHAS)/MEX-COG Folder/Data & Documentation/Version 3 - Jan 2020/STATA/Anthropometrics_and_Biomarkers_Mex_Cog_2016.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library '/Users/almichae/Dropbox (MHAS)/MEX-COG Folder/Data & Documentation/Version 3 - Jan 2020/STATA/' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = Anthropo ;

proc format library = library ;
   value CLAVESUBHOG
      0 = '00.Baseline HH'  
      1 = '01.No change, HH contains NP=010'  
      2 = '02.No change, HH contains NP=020'  
      3 = '03.No change, HH contains NP=011'  
      4 = '04.No change, HH contains NP=021'  
      11 = '11.New HH contains NP=010'  
      12 = '12.New HH contains NP=020'  
      13 = '13.New HH contains NP=011'  
      14 = '14.New HH contains NP=021'  
      15 = '15.New HH contains NP=012'  
      16 = '16.New HH contains NP=022'  
      17 = '17.New HH contains NP=013'  
      18 = '18.New HH contains NP=023'  
      31 = '31.NP=010 Deceased'  
      32 = '32.NP=020 Deceased'  
      33 = '33.NP=011 Deceased'  
      34 = '34.NP=021 Deceased'  
      35 = '35.NP=012 Deceased'  
      36 = '36.NP=022 Deceased'  
      37 = '37.NP=022 Deceased'  
      38 = '38.NP=023 Deceased'  
      70 = '70.NP=010 & NP=020 separated, reunited'  
      71 = '71.Subsequent NP=010 HH separated, reunited'  
      72 = '72.Subsequent NP=020 HH separated, reunited'  
      77 = '77.HH lost to follow-up/Not contacted'  
      88 = '88.Deceased before current wave'  
      99 = '99.Not yet part of the study' ;
   value SEX
      1 = '1.Male'  
      2 = '2.Female' ;
   value TAM_LOC
      1 = '1.Population = 100,000+'  
      2 = '2.Population = 15,000 - 99,999'  
      3 = '3.Population = 2,500 - 14,999'  
      4 = '4.Population <2,500' ;
   value PHASE
      1 = '1.Phase 1'  
      2 = '2.Phase 2' ;
   value RESULT
      1 = '1.Interviewed/Entrevistado'  
      2 = '2.Incomplete/Incompleto'  
      3 = '3.Refusal/Rechazo'  
      4 = '4.Lost to Follow-up/No encontrado'  
      5 = '5.Deceased/Fallecido'  
      6 = '6.Subject not fit for interview & without adequeta informant/Sujeto discapacitado o no adecuado' ;
   value MA_Q1_S_16F
      999 = '999: Did not get measurement/No se tomó medición' ;
   value MA_Q1_D_16F
      999 = '999: Did not get measurement/No se tomó medición' ;
   value MA_Q1_P_16F
      999 = '999: Did not get measurement/No se tomó medición' ;
   value MA_Q3_16F
      1 = '1: No issue/Sin problema'  
      2 = '2: Physical limitation/Problema físico'  
      3 = '3: No cooperation/No coopero'  
      4 = '4: Refused/Se negó' ;
   value MA_Q4_16F
      1 = '1: Yes/Sí'  
      2 = '2: No/No' ;
   value MA_Q5_16F
      1 = '1: Yes/Sí'  
      2 = '2: No/No' ;
   value MA_Q6_16F
      1 = '1: Yes/Sí'  
      2 = '2: No/No' ;
   value MA_Q7_16F
      995 = '995: Tried, but could not/Trató, pero no pudo'  
      996 = '996: Did not try/No se intentó'  
      997 = '997: Cannot stand/No puede pararse'  
      999 = '999: Refused to provide/Rehusó hacerla' ;
   value MA_Q7_1_16F
      995 = '995: Tried, but could not/Trató, pero no pudo'  
      996 = '996: Did not try/No se intentó'  
      997 = '997: Cannot stand/No puede pararse'  
      999 = '999: Refused to provide/Rehusó hacerla' ;
   value MA_Q8_16F
      995 = '995: Tried, but could not/Trató, pero no pudo'  
      996 = '996: Did not try/No se intentó'  
      997 = '997: Cannot stand/No puede pararse'  
      999 = '999: Refused to provide/Rehusó hacerla' ;
   value MA_Q8_1_16F
      995 = '995: Tried, but could not/Trató, pero no pudo'  
      996 = '996: Did not try/No se intentó'  
      997 = '997: Cannot stand/No puede pararse'  
      999 = '999: Refused to provide/Rehusó hacerla' ;
   value MA_Q9_16F
      995 = '995: Tried, but could not/Trató, pero no pudo'  
      996 = '996: Did not try/No se intentó'  
      997 = '997: Cannot stand/No puede pararse'  
      999 = '999: Refused to provide/Rehusó hacerla' ;
   value MA_Q9_1_16F
      995 = '995: Tried, but could not/Trató, pero no pudo'  
      996 = '996: Did not try/No se intentó'  
      997 = '997: Cannot stand/No puede pararse'  
      999 = '999: Refused to provide/Rehusó hacerla' ;
   value MA_Q13_S_16F
      999 = '999: Did not get measurement/No se tomó medición' ;
   value MA_Q13_D_16F
      999 = '999: Did not get measurement/No se tomó medición' ;
   value MA_Q13_P_16F
      999 = '999: Did not get measurement/No se tomó medición' ;
   value MA_Q15_16F
      1 = '1: No issue/Sin problema'  
      2 = '2: Physical limitation/Problema físico'  
      3 = '3: No cooperation/No cooperó'  
      4 = '4: Refused/Se negó' ;
   value MA_Q16_1_R_16F
      94 = '94: Missing or injured extremity/Extremidad faltante o lastimada'  
      95 = '95: Tried, but could not do/Trató'  
      96 = '96: No safe attempt could be safe/No se intentó por seguridad'  
      97 = '97: Cannot stand/No puede pararse'  
      99 = '99: Refused/Rehusó hacerla' ;
   value MA_Q16_3_L_16F
      94 = '94: Missing or injures extremity/Extremidad faltante o lastimada'  
      95 = '95: Tried, but could not/Trató'  
      96 = '96: No attempt was made due to safety/No se intentó por seguridad'  
      97 = '97: Cannot stand/No puede pararse'  
      99 = '99: Refused/Rehusó hacerla' ;
   value MA_Q18_1_16F
      1 = '1: Tried, but could not/Trató, pero no pudo'  
      2 = '2: The participant could not maintain position without help/El participante no pudo mantener su posición sin ayuda'  
      3 = '3: No attempt,interviewer did not feel safe/No intentó, usted se sintió inseguro'  
      4 = '4: No attempt, the  participant did not feel safe /No intentó, el participante se sintió inseguro'  
      5 = '5: The participant could not   understand instructions/El participante no pudo entender las instrucciones'  
      6 = '6: Other/Otro'  
      7 = '7: Refused/Rehusó hacerla' ;
   value MA_Q19_16F
      1 = '1: None/Ninguna'  
      2 = '2: Cane/Bastón'  
      3 = '3: Other/Otra' ;
   value MA_Q21_1_16F
      1 = '1: Tried, but could not/Trató, pero no pudo'  
      2 = '2: The participant could not maintain position without help/El participante no pudo mantener su posición sin ayuda'  
      3 = '3: No attempt,interviewer did not feel safe/No intentó, usted se sintió inseguro'  
      4 = '4: No attempt, the  participant did not feel safe /No intentó, el participante se sintió inseguro'  
      5 = '5: The participant could not   understand instructions/El participante no pudo entender las instrucciones'  
      6 = '6: Other/Otro'  
      7 = '7: Refused/Rehusó hacerla' ;
   value MA_Q22_16F
      1 = '1: None/Ninguna'  
      2 = '2: Cane/Bastón'  
      3 = '3: Other/Otra' ;
   value MA_Q23_16F
      1 = '1: Yes, with both hands/Sí, con ambas manos'  
      2 = '2: Yes, only with the right hand/Sí, sólo con la mano derecha'  
      3 = '3: Yes, only with the left hand/Sí, sólo con la mano izquierda'  
      4 = '4: It is not possible to do the test with either hand/No es posible realizar la prueba con ninguna mano' ;
   value MA_Q24_16F
      1 = '1: No attempt,interviewer did not feel safe/No intentó, se sintió inseguro'  
      2 = '2: No attempt, the  participant did not feel safe /No intentó, el participante se sintió inseguro'  
      3 = '3: Participant refused/El participante rehusó hacer la prueba'  
      4 = '4: The participant could not understand the instructions/El participante no pudo entender las instrucciones'  
      5 = '5: The participant could not participate due to surgery, inflammation, pain, etc., or other health condition /El participante no pudo participar debido a una cirugía, inflamación, dolor, etc.; u otra situación de salud'  
      6 = '6: Other/Otro' ;
   value MA_Q25_16F
      1 = '1: Right/Derecha'  
      2 = '2: Left/Izquierda'  
      3 = '3: Both hands/Ambas manos' ;
   value MA_Q26_1_16F
      993 = '993: Tried, but could not/Intentó pero no pudo'  
      999 = '999: Did not try/No lo intentó' ;
   value MA_Q26_2_16F
      993 = '993: Tried, but could not/Intentó pero no pudo'  
      999 = '999: Did not try/No lo intentó' ;
   value MA_Q27_1_16F
      993 = '993: Tried, but could not/Intentó pero no pudo'  
      999 = '999: Did not try/No lo intentó' ;
   value MA_Q27_2_16F
      993 = '993: Tried, but could not/Intentó pero no pudo'  
      999 = '999: Did not try/No lo intentó' ;
   value MA_Q28_16F
      1 = '1: Yes/Sí'  
      2 = '2: No/No' ;
   value MA_Q30_16F
      1 = '1: No issue/Sin problema'  
      2 = '2: Does not understand instructions/No pudo entender las instrucciones'  
      3 = '3: Has hemophilia/Tiene hemofilia'  
      4 = '4: Tried but it was not possible to obtain sample/Se intento, pero no fue posible obtener muestra'  
      5 = '5: Not engouh sample was obtained/Muestra no es suficiente'  
      6 = '6: Refused/Rehusa'  
      7 = '7: Other/Otra' ;
   value MA_Q31_16F
      1 = '1: No issue/Sin problema'  
      2 = '2: Does not understand instructions/No pudo entender las instrucciones'  
      3 = '3: Has hemophilia/Tiene emofilia'  
      4 = '4: Tried but it was not possible to obtain sample/Se intento, pero no fue posible obtener muestra'  
      5 = '5: Not engouh sample was obtained/Muestra no es suficiente'  
      6 = '6: Refused/Rehusa'  
      7 = '7: Other/Otra' ;
   value MA_Q32_1_16F
      1 = '1: No issue/Sin problema'  
      2 = '2: Does not understand instructions/No'  
      3 = '3: Tried but it was not possible to obtain sample/Se intento, pero no fue posible obtener muestra'  
      4 = '4: Not enough sample was obtained/Muestra no es suficiente'  
      5 = '5: Refused/Rehusa'  
      6 = '6: Other/Otra' ;
   value MA_Q33_16F
      999 = '99.9: >13'  
     .S = '.s: Skip / Salto' ;
   value MA_Q34_16F
      1 = '1: No issue/Sin problema'  
      2 = '2: Does not understand instructions/No pudo entender las instrucciones'  
      3 = '3: Tried but it was not possible to obtain sample/Se intento, pero no fue posible obtener muestra'  
      4 = '4: Not engouh sample was obtained/Muestra no es suficiente'  
      5 = '5: Refused/Rehusa'  
      6 = '6: Other/Otra' ;
   value MA_Q35_16F
      888 = '88.8: <3'  
      999 = '99.9: >13'  
     .S = '.s: Skip / Salto' ;
   value CRP_CAT
      1 = '1. <1 mg/dL'  
      2 = '2. 1 to 3 mg/dL'  
      3 = '3. >=3 mg/dL' ;
   value HDLC_CAT
      1 = '1. < 40 mg/dL'  
      2 = '2. >= 40 mg/dL' ;
   value CHOL_CAT
      1 = '1. <200 mg/dL'  
      2 = '2. 200-239 mg/dL'  
      3 = '3. >=240 mg/dL' ;
   value TSH
      100 = '> 100.0000' ;
   value TSH_CAT
      1 = '1. <200 mg/dL'  
      2 = '2. 200-239 mg/dL'  
      3 = '3. >=240 mg/dL' ;
   value VIT_D_CAT
      1 = '1. <20 ng/mL'  
      2 = '2. >=20 ng/mL' ;

DATA library.&dataset ;
INFILE datafile LRECL=601;
INPUT
   cunicah  1-5             np  6-7                  subhog_15  8-9        
   age_15  10-12            sex_15  13               tam_loc_15  14        
   yrschool  15-16          phase_mxcog_16  17       res_mxcog_comp_16 $ 18-21
   res_antro_16  22         ma_q1_s_16  23-25        ma_q1_d_16  26-28     
   ma_q1_p_16  29-31        ma_q2_h_16 $ 32-33       ma_q2_m_16 $ 34-35    
   ma_q2_ap_16 $ 36-37      ma_q3_16  38             ma_q4_16  39          
   ma_q5_16  40             ma_q6_16  41             ma_q7_16  42-57       
   ma_q7_1_16  58-73        ma_q8_16  74-89          ma_q8_1_16  90-105    
   ma_q9_16  106-121        ma_q9_1_16  122-137      ma_q13_s_16  138-140  
   ma_q13_d_16  141-143     ma_q13_p_16  144-146     ma_q14_h_16 $ 147-148 
   ma_q14_m_16 $ 149-150    ma_q14_ap_16 $ 151-152   ma_q15_16  153        
   ma_q16_1_r_16  154-155   ma_q16_2_r_16 $ 156-159   ma_q16_3_l_16  160-161
   ma_q16_4_l_16 $ 162-165   ma_q17_16 $ 166-169      ma_q18_1_16  170      
   ma_q18_e_16 $ 171-273    ma_q19_16  274           ma_q20_16 $ 275-278   
   ma_q21_1_16  279         ma_q21_e_16 $ 280-328    ma_q22_16  329        
   ma_q23_16  330           ma_q24_16  331           ma_q24_1_16 $ 332-333 
   ma_q25_16  334           ma_q26_1_16  335-351     ma_q26_2_16  352-368  
   ma_q27_1_16  369-385     ma_q27_2_16  386-402     ma_q28_16  403        
   ma_q29_16 $ 404-405      ma_q30_16  406           ma_q30_e_16 $ 407-408 
   ma_q31_16  409           ma_q31_e_16 $ 410-411    ma_q32_1_16  412      
   ma_q32_2_16 $ 413-463    ma_q33_16  464-479       ma_q34_16  480        
   ma_q34_e_16 $ 481-541    ma_q35_16  542-557       biomarkers_16  558    
   crp_16  559-564          crp_cat_16  565          hdlc_16  566-567      
   hdlc_rev_16  568-583     hdlc_cat_16  584         chol_16  585-587      
   chol_cat_16  588         tsh_16  589-595          tsh_cat_16  596       
   vit_d_16  597-600        vit_d_cat_16  601      ;                       

LABEL
   cunicah = "clave única del hogar"
   np = "número de persona"
   subhog_15 = "2015 sub-household identifier"
   age_15 = "Age 2015"
   sex_15 = "Sex (Male=1)"
   tam_loc_15 = "Locality size 2015"
   yrschool = "Years of education"
   phase_mxcog_16 = "Mex-Cog 2016 Phase"
   res_mxcog_comp_16 = "Mex-Cog Result for Each Component(String):COG/INF/ANTRO/BIOM"
   res_antro_16 = "Result of Atropometric Measures"
   ma_q1_s_16 = "Sistolic pressure. 1st measurement / Medida de presion sistolica. 1era medicion"
   ma_q1_d_16 = "Diastolic pressure. 1st measurement / Medida de presion diastolica. 1era medicio"
   ma_q1_p_16 = "Pulse. First measurement / Pulso. Primera medicion"
   ma_q2_h_16 = "Time 1st blood pressure measurement. Hour / Hora de la 1era toma. Hora"
   ma_q2_m_16 = "Time 1st blood pressure measurement. Minutes / Hora de la 1era toma. Minutos"
   ma_q2_ap_16 = "Time 1st blood pressure measurement. AM/PM / Hora de la 1era toma. AM/PM"
   ma_q3_16 = "Result of first measurement. / Resultado de la medicion. Primera medicion"
   ma_q4_16 = "Can the person stand unsupported? / ¿La persona puede pararse sin apoyo?"
   ma_q5_16 = "Does the person have a visible spinal curvature? / ¿La persona tiene una curvatu"
   ma_q6_16 = "Can the person get a proper upright posture? / ¿Se puede obtener una postura rec"
   ma_q7_16 = "Height. First measurement / Estatura. Primera medicion"
   ma_q7_1_16 = "Height. Second measurement / Estatura. Segunda medicion"
   ma_q8_16 = "Weight. First measurement / Peso. Primera medicion"
   ma_q8_1_16 = "Weight. Second measurement / Peso. Segunda medicion"
   ma_q9_16 = "Waist. First measurement / Cintura. Primera medicion"
   ma_q9_1_16 = "Waist. Second measurement / Cintura. Segunda medicion"
   ma_q13_s_16 = "Sistolic pressure. 2nd measurement / Medida de presion sistolica. 2da medicion"
   ma_q13_d_16 = "Diastolic pressure. 2nd measurement / Medida de presion diastolica. 2da medicion"
   ma_q13_p_16 = "Pulse. Second measurement / Pulso. Segunda medicion"
   ma_q14_h_16 = "Time 2nd blood pressure measurement. Hour / Hora de la 2da toma. Hora"
   ma_q14_m_16 = "Time 2nd blood pressure measurement. Minutes / Hora de la 2da toma. Minutos"
   ma_q14_ap_16 = "Time 2nd blood pressure measurement. AM/PM / Hora de la 2da toma. AM/PM"
   ma_q15_16 = "Result of second measurement. / Resultado de la medicion. Segunda medicion"
   ma_q16_1_r_16 = "Balance. Right foot / Balance. Pie derecho"
   ma_q16_2_r_16 = "Duration of balance. Right foot / Tiempo de balance. Pie derecho"
   ma_q16_3_l_16 = "Balance. Left foot / Balance. Pie izquierdo"
   ma_q16_4_l_16 = "Duration of balance. Left foot / Tiempo de balance. Pie izquierdo"
   ma_q17_16 = "Walking speed. First test / Velocidad al caminar. Primera prueba"
   ma_q18_1_16 = "If the participant did not attempt or failed the test, indicate reason / Sujeto "
   ma_q18_e_16 = "If the participant did not attempt or failed the test, indicate reason. Other / "
   ma_q19_16 = "Aids used during first test. / Ayuda en la primera prueba de velocidad al camina"
   ma_q20_16 = "Walking speed. Second test / Velocidad al caminar. Segunda prueba"
   ma_q21_1_16 = "If the participant did not attempt or failed the test, indicate reason (Test 2) "
   ma_q21_e_16 = "If the participant did not attempt or failed the test, indicate reason. Other (T"
   ma_q22_16 = "Aids used during second test. / Ayuda en la segunda prueba de velocidad al camin"
   ma_q23_16 = "Do you feel it is safe for you to do this measurement? Hand grip test / ¿Siente "
   ma_q24_16 = "Enter the reason that the test was not performed. Other / Sujeto no realizo la p"
   ma_q24_1_16 = "Enter the reason that the test was not performed. Other / Sujeto no realizo la p"
   ma_q25_16 = "What is your dominant hand, with which you perform most things? / ¿Cuál es su ma"
   ma_q26_1_16 = "Hand grip test. First measurement left hand / Medicion de fuerza de presion. Pri"
   ma_q26_2_16 = "Hand grip test. Second measurement left hand / Medicion de fuerza de presion. Se"
   ma_q27_1_16 = "Hand grip test. First measurement right hand / Medicion de fuerza de presion. Pr"
   ma_q27_2_16 = "Hand grip test. Second measurement right hand / Medicion de fuerza de presion. S"
   ma_q28_16 = "Subject completed the handgrip test / Sujeto realizo la prueba de presion de fue"
   ma_q29_16 = "Hours since last meal/Horas desde la ultima comida"
   ma_q30_16 = "Blood sample Result (red tube) / Resultado de muestra de sangre (tubo rojo)"
   ma_q30_e_16 = "Blood sample RES (red tube)-Other / Resultado muestra de sangre(tubo rojo)-Otro"
   ma_q31_16 = "Blood sample Result (lavender tube) / Resultado muestra de sangre (tubo lavanda)"
   ma_q31_e_16 = "Blood sample RES (lavender tube) Other / Resultado muestra de sangre (tubo lav.)"
   ma_q32_1_16 = "Application of glycosylated hemoglobin. / Sujeto realizo prueba de glucosa."
   ma_q32_2_16 = "Application of glycosylated hemoglobin. Other / Sujeto realizo prueba de glucosa"
   ma_q33_16 = "Result of glycosylated hemoglobin.  / Resultado de la hemoglobina glucosilada."
   ma_q34_16 = "Lead result / Resultado de prueba de plomo"
   ma_q34_e_16 = "Lead result. Other / Resultado de prueba de plomo. Especificado"
   ma_q35_16 = "Lead / Plomo"
   biomarkers_16 = "Mex-Cog 2016 Sample with Biomarkers"
   crp_16 = "C-Reactive Protein Lab Result mg/dL"
   crp_cat_16 = "C-Reactive Protein - Categories"
   hdlc_16 = "High-Density Lipoprotein Cholesterol Lab Results mg/dL"
   hdlc_rev_16 = "High-Density Lipoprotein Cholesterol Lab Results - REVISED mg/dL"
   hdlc_cat_16 = "REVISED High-Density Lipoprotein Cholesterol - Categories"
   chol_16 = "Cholesterol Lab Results mg/dL"
   chol_cat_16 = "Cholesterol Lab Results - Categories"
   tsh_16 = "TSH Lab results uIU/mL"
   tsh_cat_16 = "TSH Lab results - Categories"
   vit_d_16 = "25-Hydroxy Vitamin D Lab results ng/mL"
   vit_d_cat_16 = "25-Hydroxy Vitamin - Categories" ;

FORMAT
   subhog_15 CLAVESUBHOG.   sex_15 SEX.              tam_loc_15 TAM_LOC.   
   phase_mxcog_16 PHASE.    res_antro_16 RESULT.     ma_q1_s_16 MA_Q1_S_16F.
   ma_q1_d_16 MA_Q1_D_16F.   ma_q1_p_16 MA_Q1_P_16F.   ma_q3_16 MA_Q3_16F.   
   ma_q4_16 MA_Q4_16F.      ma_q5_16 MA_Q5_16F.      ma_q6_16 MA_Q6_16F.   
   ma_q7_16 MA_Q7_16F.      ma_q7_1_16 MA_Q7_1_16F.   ma_q8_16 MA_Q8_16F.   
   ma_q8_1_16 MA_Q8_1_16F.   ma_q9_16 MA_Q9_16F.      ma_q9_1_16 MA_Q9_1_16F.
   ma_q13_s_16 MA_Q13_S_16F.   ma_q13_d_16 MA_Q13_D_16F.   ma_q13_p_16 MA_Q13_P_16F.
   ma_q15_16 MA_Q15_16F.    ma_q16_1_r_16 MA_Q16_1_R_16F.   ma_q16_3_l_16 MA_Q16_3_L_16F.
   ma_q18_1_16 MA_Q18_1_16F.   ma_q19_16 MA_Q19_16F.    ma_q21_1_16 MA_Q21_1_16F.
   ma_q22_16 MA_Q22_16F.    ma_q23_16 MA_Q23_16F.    ma_q24_16 MA_Q24_16F. 
   ma_q25_16 MA_Q25_16F.    ma_q26_1_16 MA_Q26_1_16F.   ma_q26_2_16 MA_Q26_2_16F.
   ma_q27_1_16 MA_Q27_1_16F.   ma_q27_2_16 MA_Q27_2_16F.   ma_q28_16 MA_Q28_16F. 
   ma_q30_16 MA_Q30_16F.    ma_q31_16 MA_Q31_16F.    ma_q32_1_16 MA_Q32_1_16F.
   ma_q33_16 MA_Q33_16F.    ma_q34_16 MA_Q34_16F.    ma_q35_16 MA_Q35_16F. 
   crp_cat_16 CRP_CAT.      hdlc_cat_16 HDLC_CAT.    chol_cat_16 CHOL_CAT. 
   tsh_16 TSH.              tsh_cat_16 TSH_CAT.      vit_d_cat_16 VIT_D_CAT. ;


LENGTH
   cunicah 4                np 3                     subhog_15 3           
   age_15 4                 sex_15 3                 tam_loc_15 3          
   yrschool 3               phase_mxcog_16 3         res_antro_16 3        
   ma_q1_s_16 4             ma_q1_d_16 4             ma_q1_p_16 4          
   ma_q3_16 3               ma_q4_16 3               ma_q5_16 3            
   ma_q6_16 3               ma_q13_s_16 4            ma_q13_d_16 4         
   ma_q13_p_16 4            ma_q15_16 3              ma_q16_1_r_16 3       
   ma_q16_3_l_16 3          ma_q18_1_16 3            ma_q19_16 3           
   ma_q21_1_16 3            ma_q22_16 3              ma_q23_16 3           
   ma_q24_16 3              ma_q25_16 3              ma_q28_16 3           
   ma_q30_16 3              ma_q31_16 3              ma_q32_1_16 3         
   ma_q34_16 3              biomarkers_16 3          crp_cat_16 3          
   hdlc_16 3                hdlc_cat_16 3            chol_16 4             
   chol_cat_16 3            tsh_cat_16 3             vit_d_cat_16 3 ;

    

RUN ;
